apiVersion: 1

contactPoints:
  - orgId: 1
    name: SNS
    receivers:
      - uid: sns-server-room
        type: sns
        settings:
          topic_arn: arn:aws:sns:us-east-1:<AWS_ID_ACCOUNT>:grafana-sns
        disableResolveMessage: false
