apiVersion: 1

datasources:
  - name: IoT-PostgreSQL
    uid: iot-postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_ENDPOINT}:5432
    database: iotrds
    user: iotadmin
    isDefault: true
    editable: true

    jsonData:
      sslmode: require

    secureJsonData:
      password: ${POSTGRES_PASSWORD}
