apiVersion: 1

datasources:
  - name: IoT-PostgreSQL
    uid: iot-postgres
    type: postgres
    access: proxy
    url: iot-rds-iotrds-yxpyvnrvhixy.catqw48y8uxg.us-east-1.rds.amazonaws.com:5432
    database: iotrds
    user: iotadmin
    isDefault: true
    editable: true
    orgId: 1

    jsonData:
      sslmode: require

    secureJsonData:
      password: SuperPasswordSeguro123!
